### ISSUE TITLE
如何添加按键震动

### ISSUE THREAD

**Issue by Sliots-SZU** [SValence/SafeKeyboard#10]
我想在它点击按键的时候震动
在SafeKeyboard.java ->onKey里面加入

Vibrator vibrator = (Vibrator) getSystemService(Context.VIBRATOR_SERVICE);

会出现
java.lang.IllegalStateException: System services not available to Activities before onCreate()

不知道如何解决，请教一下。

**Comment by SValence** [comment]
这个错误就是在Activity没有创建完成的时候调用了onKey，我今天下班后看一下这个问题。出一个解决办法。

**Comment by SValence** [comment]
你好，我这边在onKey里设置振动是没有问题的。你再检查下是否有问题吧。这里是我的代码截图

**Comment by SValence** [comment]
![代码](https://user-images.githubusercontent.com/20383015/68394875-976faa80-01a9-11ea-9998-79e2fb3fcd9c.png)

**Comment by Sliots-SZU** [comment]
打扰您了。发现是早上放到了onPress()里去了，并且没有加上 `mContext.`时就会报错
`Vibrator vibrator = (Vibrator) getSystemService(Context.VIBRATOR_SERVICE);`
`Vibrator vibrator = (Vibrator) mContext.getSystemService(Context.VIBRATOR_SERVICE);`
现在可以正常使用了，感谢您。
