### ISSUE TITLE
用起来略微繁琐

### ISSUE THREAD

**Issue by gitzsl** [SValence/SafeKeyboard#11]
感谢作者的分享！功能都实现了，就是用起来略微繁琐哈~要能做成系统弹窗，支持一键调用就好了

**Comment by SValence** [comment]
谢谢使用，我一直在维护这个项目，也正在考虑怎么才能更方便的使用。
如果你有什么建议都可以分享一下。
有新的实现和功能我会第一时间发布出来。

**Comment by SValence** [comment]
一键调用已更新
