### ISSUE TITLE
如何取消按键选中放大效果，感谢。

### ISSUE THREAD

**Issue by chocozhao** [SValence/SafeKeyboard#12]
如何取消按键选中放大效果，需要怎么做才能解决？

**Comment by SValence** [comment]
你说的按键放大显示，是不是这个意思？比如说按下  a  键，在 a 上当也显示出来一个白底蓝字的功能吗？
如果是的话，在SafeKeyboardView声明的地方有个forbidPreview设置为true就可以了，或者在SafeKeyboard对象设置setForbidPreview也行

**Comment by SValence** [comment]
SafeKeyboard对象设置setForbidPreview，下个版本会增加xml属性开关功能

**Comment by chocozhao** [comment]
您好呀，是的，就是你说的这种情况，我查看完SafeKeyboardView这个类并没有发现有forbidPreview这个字段，如果有，大佬方便一下指示一下么？或者大佬方便现在更新个版本么。感谢！！！！

**Comment by SValence** [comment]
![image](https://user-images.githubusercontent.com/20383015/70137588-387a5400-16c9-11ea-857f-c08be03c3658.png)
![image](https://user-images.githubusercontent.com/20383015/70137656-68c1f280-16c9-11ea-9dc7-b37d77e92ef4.png)
这样调用就可以了。这个版本就支持

**Comment by chocozhao** [comment]
抱歉，我找不到的原因是我代码是比较旧的版本了。所以没找到，目前已经解决，感谢大佬。
