### ISSUE TITLE
如何随机布局呢，目前在您的基础之上，想要全键盘随机的一个效果。

### ISSUE THREAD

**Issue by MaleWxt** [SValence/SafeKeyboard#13]

**Comment by SValence** [comment]
请参考随机数字键盘的实现模式, 先取出所有的字母按键值 keys，
![image](https://user-images.githubusercontent.com/20383015/89531185-6a2c5780-d822-11ea-8b64-bf11e0b6aa5f.png)

显示前进行刷新各字母位置，实现也是参考下面的随机数字键盘，把 10 换成 26 即可，把每个字母与固定的数据绑定就行了。
![image](https://user-images.githubusercontent.com/20383015/89531460-dd35ce00-d822-11ea-85ee-e41a6c395878.png)

希望能够帮到你

**Comment by MaleWxt** [comment]
> 请参考随机数字键盘的实现模式, 先取出所有的字母按键值 keys，
> ![image](https://user-images.githubusercontent.com/20383015/89531185-6a2c5780-d822-11ea-8b64-bf11e0b6aa5f.png)
> 
> 显示前进行刷新各字母位置，实现也是参考下面的随机数字键盘，把 10 换成 26 即可，把每个字母与固定的数据绑定就行了。
> ![image](https://user-images.githubusercontent.com/20383015/89531460-dd35ce00-d822-11ea-85ee-e41a6c395878.png)
> 
> 希望能够帮到你

ok，明白了，我尝试来修改一下。

**Comment by MaleWxt** [comment]
![Uploading image.png…]()
这里的随机逻辑，我看出来是将数据打乱，并且每个位置上的key/value刷新了一下，但是数字随机中这个48的数值，我没太明白，是对应的code是吗，如果换成字母键盘或者符号键盘的话，这部分的逻辑应该是怎么样的呢，请赐教！谢谢！
