### ISSUE TITLE
求解图中的数字困惑。

### ISSUE THREAD

**Issue by MaleWxt** [SValence/SafeKeyboard#14]
![image](https://user-images.githubusercontent.com/18377645/90202682-ecafab00-de10-11ea-92d1-9587357ca3a6.png)
目前我尝试了修改字符键盘跟字母键盘随机，但是并未成功，图中的数字是我比较疑惑的地方，针对于数字键盘的随机，字符跟字母键盘是否需要在onDraw方法中做其他处理呢？请赐教。

**Comment by SValence** [comment]
晚上我试试实现吧

**Comment by MaleWxt** [comment]
> 晚上我试试实现吧

ok，我也正在尝试，目前没有实现。

**Comment by SValence** [comment]
10 代表 10 个数字 0-9, 字母键盘时应改为 26, 代表 a-z, 并与 0-25 相对应。如下图
![image](https://user-images.githubusercontent.com/20383015/90245028-7472d500-de64-11ea-9dd7-205cc0333468.png)
 
48 代表 数字 0 的 code 48, 这里实现随机功能是取巧实现的, 0-9 的 code 是 48-57, 字母键盘时应改为 97, a-z code 为 97-122，
如下图
![image](https://user-images.githubusercontent.com/20383015/90245267-ef3bf000-de64-11ea-9ac4-570869cddee0.png)

需要更新随机位置时调用以下方法即可
![image](https://user-images.githubusercontent.com/20383015/90245352-15fa2680-de65-11ea-9745-bdc2bfaaaf1b.png)

另外, 切换大小写时不宜重新随机一遍字母排序, 所以可加上以下代码
![image](https://user-images.githubusercontent.com/20383015/90245456-4b067900-de65-11ea-913c-28cce4adcc58.png)

至此字母随机功能已完成，可以参考数字随机功能，支持在xml布局文件及SafeKeyboard中增加 开启/关闭 字母随机显示功能
