### ISSUE TITLE
反应慢

### ISSUE THREAD

**Issue by lidaming940614** [SValence/SafeKeyboard#16]
我直接吧源文拖过来用的，但是我的项目是kotlin写的，用的androidx，软键盘用起来响应非常慢，按快了软键盘根本反应不过来

**Comment by SValence** [comment]
描述起来不是很好理解，做个动图吧

**Comment by lidaming940614** [comment]
就是我点击快了，键盘还没反应过来，比如我1秒点击了3个数字，但是editview只显示了1个数字

**Comment by lidaming940614** [comment]
找到问题了，我的原因，不好意思啊
