### ISSUE TITLE
如题

### ISSUE THREAD

**Issue by candebbs** [SValence/SafeKeyboard#2]
如果布局中最外一层是ScrollView，且editText在最下面，是有问题，有空看下吧。

**Comment by SValence** [comment]
好的，这周末有空我查一下问题。多谢

**Comment by candebbs** [comment]
这个解决了，可以多套一层布局来解决，同时要监听输入法，把editText顶上去的

**Comment by SValence** [comment]
我这测试了没有出现这个问题，在github上不方便交流，可以的加个联系方式？1316855120@qq.com
