### ISSUE TITLE
EditText的id相同时会出现自定义键盘和系统键盘同时出现的问题

### ISSUE THREAD

**Issue by espimx** [SValence/SafeKeyboard#23]
在页面上使用include标签，include的布局中包含EditText，引入多个相同的include的布局，就能复现

**Comment by MazheDroid** [comment]
兄弟，我碰到了相同的问题，你有解决吗？

**Comment by SValence** [comment]
晚上我来测试一下

**Comment by SValence** [comment]
非常感谢你们的使用和反馈，谢谢。
目前问题已修复！源码已更新

**Comment by espimx** [comment]
我当时也是改成使用Tag来作为唯一Key的方法，作者你可真靓仔！
