### ISSUE TITLE
Dialog中如何使用？

### ISSUE THREAD

**Issue by ttxz** [SValence/SafeKeyboard#24]
如题，如果是类似AlertDialog，Dialog包含输入框，应该如何使用

**Comment by SValence** [comment]
使用 DialogFragment，自定义布局文件

**Comment by SValence** [comment]
参考(https://github.com/SValence/SafeKeyboard/tree/master/SafeKeyboardLib/src/main/java/com/valence/safe/keyboard)/SafeKeyboardDialogFragment.java

**Comment by SValence** [comment]
参考项目文件：https://github.com/SValence/SafeKeyboard/blob/master/SafeKeyboardLib/src/main/java/com/valence/safe/keyboard/SafeKeyboardDialogFragment.java

**Comment by ttxz** [comment]
@SValence 您好，看了下，好像只能把dialog按照DialogFragment形式设置为全局，但是项目中dialog太多，修改起来太繁琐，由于项目是运行自助设备上，所以重新编译修改了AOSP输入法源码，暂时先使用输入法方式（需要多安装一个应用，手机上就没办法了，得使用自定义键盘了），感谢作者封装，谢谢！
