### ISSUE TITLE
怎么把字母联想到汉字呢？

### ISSUE THREAD

**Issue by zz005** [SValence/SafeKeyboard#25]
假如我输入了一个字母 不直接放到 输入框 而是像系统键盘一样在上方显示字母联想到的汉字作为候选字 点击确定才写入输入框
目的就是监听候选字 有相关的方法吗

**Comment by SValence** [comment]
你这个需求就是要输入汉字，那不就成了输入法了啊？

想做这种类似输入法的话也是可以的
1. 首先，在自定义键盘界面增加一个 布局, 用来显示输入的字母和联想出来的汉字
2. 然后，在 SafeKeyboard.java 类的 public void onKey(int primaryCode, int[] keyCodes) {} 方法中拦截 editable.replace(...) 的输入内容，让输入字母的时候不更新到输入框，并在这里去执行汉字联想程序
3. 最后，当目标汉字出现的时候，选中汉字后在执行 editable.replace(...) 功能

不过汉字联想程序就需要你自己去做了，最近一段时间其他工作比较忙，我还没有增加这个功能的时间。
你可以参考一下试试看。

**Comment by zz005** [comment]
好的 谢谢

**Comment by codezc** [comment]
@zz005 大佬实现了吗，可以分享一下吗
