### ISSUE TITLE
大写锁定后输入$#_等特殊字符后，再次输入字母，会有大写字母变成小写，且切换到小写键盘，小写字母的内容变成空白字符的情况

### ISSUE THREAD

**Issue by wqh0625** [SValence/SafeKeyboard#30]
大佬你好，我这边遇到了个问题，以下是详细描述
大写锁定后输入$#_等特殊字符后，再次输入字母，会有大写字母变成小写，且切换到小写键盘，小写字母的内容变成空白字符

请看附件视频，以及我在控制台中打印的onKey方法的返回值内容
ps（在大写的情况下，去点击大写字母W，onkey返回的内容是小写字母w。切换到小写字母，随便点击一个小写字母，onkey返回的内容是非法字符“”）

https://github.com/SValence/SafeKeyboard/assets/45384313/342add38-61de-4276-9526-305a72456b09

![20240314-112246](https://github.com/SValence/SafeKeyboard/assets/45384313/31301a71-b30a-4401-8926-841c2c1552cd)
![20240314-112300](https://github.com/SValence/SafeKeyboard/assets/45384313/2b522f52-e23e-461c-9159-f2bfe9dc3cd0)

**Comment by SValence** [comment]
你好，我测试了我手机的内容，暂时没有出现这种情况。这是每次一定会有？还是说偶然出现的？

**Comment by wqh0625** [comment]
在看到你的回复后我以为我的SafeKeyboard类与你开源的项目中的类不一致，但是我去下载对比看了文件，内容基本一致，且直接使用你开源的SafeKeyboard类，在我的app中测试，也是存在此问题的。目前是必现的

测试方法如下：首先锁定大写，之后切换到符号键盘（此时重新切换到大写键盘后，随机点击字母，大写会变成小写，问题已存在），可以尝试输入几个字符#￥？，之后切换回大写键盘，随机点击字母，大写的字母会在输入框中变成小写

麻烦再试一下呢、

**Comment by SValence** [comment]
你好，你直接替换成现在的项目文件试一下，我记得有个版本大写字母锁定后切换符号后，再切换回来会变成小写，已经修改过了，你再试一下，最后还是不行的话可以下载项目，用开源的这个项目安装一下看看会不会出现你说的问题

**Comment by SValence** [comment]
最后实在不行的话，加一下我的QQ，1316855120

**Comment by wqh0625** [comment]
大佬你好，我已经尝试替换你的项目文件，还是会出现这个问题，尝试添加你的qq但是你的qq拒绝添加好友，要不你加我下 我的QQ是 3026330480

**Comment by wqh0625** [comment]
大佬晚上好，我这边下载了你的源码，经过测试发现这个页面的EditText存在我所遇到的这个问题

视频如下所示：

https://github.com/SValence/SafeKeyboard/assets/45384313/ae5d02b0-d519-4cd8-8eeb-5cbc3be70031


但经过我测试，代码中的demo只有这个页面的第二个EditText存在这个问题，第一个并没有出现这个情况

**Comment by SValence** [comment]
问题已修复，近期更新
