### ISSUE TITLE
思考：如果两个输入框需要用安全键盘输密码，在切换时如何做到像系统输入法那样无缝切换？

### ISSUE THREAD

**Issue by zuohp** [SValence/SafeKeyboard#4]
如题，个人引发的思考

**Comment by SValence** [comment]
之后我打算更新一个可以根据输入类型 InputType 来切换键盘的版本，可以支持多个输入框公用一个View，只切换键盘类型。
实现起来也不麻烦，再初始化Keyboard的时候，把所有的 EditText 全部记录为其变量以 id 为标识，这样就可以了。
不过最近太忙了，近期可能没有精力来搞这个问题。过了这一段时间我会更新一个版本

**Comment by SValence** [comment]
已支持多个 EditText 共用一个 SafeKeyboard

**Comment by nsacer** [comment]
题主的意思应该还有一个：比如两个输入框，在第一个输入框，键盘上有“下一步”按钮，点击直接可以光标跳转到第二个输入框，并切换对应的inputType的软键盘。
