### ISSUE TITLE
大佬，我用了APPCompatEditText。。。

### ISSUE THREAD

**Issue by Adaclass** [SValence/SafeKeyboard#5]
` if (newFocus instanceof EditText) `这里只判断了EditText，然后。。就调用了` keyboardPreHide()`，然后就点击弹出来又关闭了

**Comment by SValence** [comment]
你好，这个 APPCompatEditText 是 标准 Android API 下的 EditText 的子类吗？不是的话就需要自己改造判断和转换的条件。

**Comment by SValence** [comment]
你好，我验证了一下，在示例中使用 AppCompatEditText 并没有显示后又隐藏的现象，新的示例代码已上传，你用 Demo 测试一下是否有这个问题。谢谢

**Comment by Adaclass** [comment]
好的，大佬，你回复真快

**Comment by Adaclass** [comment]
![BN7)L{)@H8(O 9{` 0${9Y2](https://user-images.githubusercontent.com/30258067/61274491-80621280-a7de-11e9-88c9-dd07e8197323.png)
原来是我的AppcompactEditText不能 instanceof  EditText

**Comment by SValence** [comment]
EditText 的子类 instanceof EditText 都是 true，那需要你查一下原因。使用过程中有什么问题，随时联系

**Comment by Adaclass** [comment]
可能是我的版本太低了，我自定义一个EditText的子类就可以，但是AppCompatEditText不行，也不能获取光标，很可能是我项目版本太低了。。。

**Comment by SValence** [comment]
好的，那你检查一下项目是不是又其他的问题，再看看有什么解决办法吧。
