### ISSUE TITLE
软键盘遮挡底部自定义的EditText该如何处理？

### ISSUE THREAD

**Issue by liminwu0626** [SValence/SafeKeyboard#8]
您好，请问软键盘遮挡底部 EditText 的逻辑在哪里写呢？

**Comment by SValence** [comment]
因为这个软键盘不是系统软键盘，所以不能通过已有的设置使键盘把输入框顶起来，
这个问题一直都有。我目前也在想解决办法。最近一段时间我有其他的事情要忙不能及时解决这个问题。但是我大致有两个思路
1.像长文本输入一样，重开一个界面输入。
2.强制View整体向上移动
具体的实现我还没有做。你可以尝试一下。如果你有其他的想法，实现之后欢迎告知。
谢谢

**Comment by SValence** [comment]
问题已修改，详见最新更新
