### ISSUE TITLE
This class was deprecated in API level 29

### ISSUE THREAD

**Issue by w2xx** [SValence/SafeKeyboard#9]
安卓api29中，键盘相关的几个自定义类都被标记过时，新版本要怎么适配呢，老哥有了解过吗

**Comment by SValence** [comment]
你好，确实没想到 KeyboardView 在Android 10 上过时，我这边的安卓10模拟器打不开，也没法验证。不过感觉上在安卓10上应该是不能直接运行了。
如果确实不行的话，只能有两种解决方法：
1. 按照提示，到AOSP拷贝源码适配到自己的项目里面（我做安卓时间也不长，这个我也没接触过）
2. 自己重新实现一个类似的 KeyboardView
你那边如果可以正常运行Android10的系统，麻烦测试一下，把target version 改成29，看是否报错，能不能运行。
验证后请把具体情况告诉我一下吧，谢谢。

**Comment by w2xx** [comment]
@SValence 我这边用安卓10模拟器试了下，可以正常运行，compile api设置为28和29都可以正常运行。貌似安卓10只是把这个类标记过时，但是还是可以使用的

**Comment by SValence** [comment]
那就是和Camera与Camera2类相似，官方已经不推荐Camera API的使用标记为过时，但是这些还是可以继续使用的。在Google完全删除这类代码之前可以继续使用。
非常感谢你的帮助，如果你需要继续使用，适配过程中有什么问题可以直接提问。
目前我也在完善这个项目，希望多提宝贵意见

**Comment by w2xx** [comment]
嗯嗯
